### ISSUE TITLE
Use contentID to retrieve and cache data

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/APCalign#25]
After meeting with @cboettig, we learnt about https://github.com/cboettig/contentid

This looks like a promising option for locally caching downloads. Plays nice with zenodo.

**Comment by wcornwell** [comment]
i don't understand how this works, but it should replace the part here: https://github.com/traitecoevo/ausflora/blob/480a46bc280d7a49a2e845a688a8a5edd7f1f02c/R/dataset_access.R#L89

**Comment by cboettig** [comment]
There are a few different options here, but no worries if none of them seem like the right way to go.  

Currently it looks like you have a copy of the data you access from a GitHub URL:
```r
version <- "0.0.2.9000"
url <- paste0("https://github.com/traitecoevo/ausflora/releases/download/",
version,"/apc.parquet")
```

So one thing we can do is to  simply "register" that URL with a contentid registry:  

```r
contentid::register(url)
```

This returns the content-hash identifier, which is kinda like a DOI.  From any computer with a network connection, we should be able to resolve that precise identifier:

```r
file <- contentid::resolve("hash://sha256/bc369b29b9c5c3e600135d8c9aa49a09cfb83e905be7d0b9607543b89a5bd0b4", store=TRUE)
```

"resolving" both discovers the registered URL and then downloads a copy to the local cache, and returns the path to the local cache.  We can now read directly from that local path:

```r
arrow::read_parquet(file)
```


### additional notes

Note: because we used `store=TRUE` on `resolve()`, we can now re-run that same `resolve()` command any time on that same computer, and it should nearly-instantly return the file path, even if we are offline, because an exact match to the ID is found in the local cache.  If for some reason the local cache is purged, it will fall back to the online resolver. 

Second note: so far, the online resolver only knows of one place to find this file, the URL we registered.  `contentid` actually just registered that URL with a little lightweight service, https://hash-archive.carlboettiger.info/, which doesn't store the data file itself, just the a fast lookup table from hash to URL.  This service should be seen merely as a temporary 'convenience'.  `contentid` can also use (one or more) local tab-separated-values table for the exact same purpose.  Once the data is deposited in a real archival repository (currently: Zenodo, DataONE, or SoftwareHeritage), contentid can automatically discover it there with _no changes_ to your R code, which always remains a simple one-line resolve of the identifier, regardless of whether the data is found only on your machine, only on a URL, or eventually in a real scientific repository.  

```r
file <- contentid::resolve("hash://sha256/bc369b29b9c5c3e600135d8c9aa49a09cfb83e905be7d0b9607543b89a5bd0b4", store=TRUE)
```

Obviously this hash is version-specific though.  Thus the R package needs to include a map from the version tag to the content identifier.  In order for the R package to permit a 'rolling' notion of 'latest version', it will need to be able to ping some remote source to look up the hash of said latest version.  This is simple enough to do by having such a key-value look up table in a file on GitHub, say.  

In such a look-up file, it is possible, though entirely optional, to add additional metadata in a standardized format, which can contain richer descriptions of the file beyond it's version, name, and content id.  I frequently use this pattern by documenting my data in the widely used schema.org/Dataset JSON standard, like so: https://github.com/ropensci/rfishbase/blob/master/inst/prov/fb.prov .  The R packages then use this to find the hash-identifier, though they could also use this to access a downloadUrl or other information.  This basically mimics what the formal data repositories do, which all have similar metadata objects for their records (usually in schema.org, among other formats).

**Comment by dfalster** [comment]
Thanks heaps for the helpful guide!

**Comment by wcornwell** [comment]
great!  looks like the right tool for the situation

**Comment by wcornwell** [comment]
this seems to work?  

```{r}
dataset_get <- function(version = default_version(),
                        path = NULL) {
    #APC
    url <- paste0("https://github.com/traitecoevo/ausflora/releases/download/",
                  version,"/apc.parquet")
    apc_hash <- contentid::register(url)
    apc_file <- contentid::resolve(apc_hash, store=TRUE, dir = path)
    APC <- arrow::read_parquet(apc_file)
```

Is it really this easy?  

I guess this will call `contentid::register` a lot somewhat unnecessarily, but I couldn't figure out how to avoid that while also making it easy to bump versions in the future.

**Comment by cboettig** [comment]
@wcornwell yup, this is correct and should work fine to provide caching, but usually I would simplify this further.  

I consider the calls to construct the URL and register the URL as something you do external to the package.  think of this as a lightweight "publishing" mechanism.  Then within the `ausflora` package, accessing the data is only the last two lines,

```r
apc_file <- contentid::resolve("hash://sha256/bc369b29b9c5c3e600135d8c9aa49a09cfb83e905be7d0b9607543b89a5bd0b4", store=TRUE), dir=path)

APC <- arrow::read_parquet(apc_file)
```

I know it looks a bit ugly to hard-code the full identifier,  `hash://sha256/bc369b29b9...`, in the R code, and you can always avoid it as you did above.  But the advantage of hardcoding the identifier is that this is an entirely "location agnostic" reference to those precise bytes of data the code is trying to read in.  You could then, say, stick this data at a bunch of different URLs and `register()` them all, so if one failed, it could resolve from another one.  Or you could forgo registering the URLs at all if the data is on a formal repo we can query by content hash.  Does that make sense?  

(I know content-based addressing is a bit of a mind-binder, we're all wired to think in terms of location-based addresses, but the basic idea is very simple and quite powerful).

**Comment by cboettig** [comment]
Right, I think the natural way to do that is have a function (or external file) that maps each version number to the corresponding object hash.  

The most trivial version of this might be a named character vector:

```r
ausflora <- c( "0.0.2.9000" = "hash://sha256/bc369b29b9c5c3e600135d8c9aa49a09cfb83e905be7d0b9607543b89a5bd0b4", 
 "0.0.1.9000" = "hash://sha256/xxxx....")
```

Then you could do:

```r
apc_file <- contentid::resolve(ausflora["0.0.2.9000"])
```

etc.  

It's easy to make this a little fancier, e.g. rather than a char vector in the R package itself, you could read this as two columns from a `.csv` file on GitHub -- that way, you could update said csv at any point without updating the R code.  Likewise, you could add a little extra R logic to determine the latest version from the names, e.g. with my named vect

```r
if(version == "latest")  version = max(names(ausflora))
apc_file <- contentid::resolve(ausflora[version])
```

you get the idea.

**Comment by cboettig** [comment]
slightly more complete example:

```r
load_apc <- function(version = "latest") {

  meta <- readr::read_csv("https://github.com/traitecovo/ausflora/tree/master/inst/extdata/versions.csv")
  ausflora <- meta$id
  names(ausflora) <- meta$version

  if(version == "latest")  version = max(names(ausflora))
  apc_file <- contentid::resolve(ausflora[version])
  
  arrow::read_parquet(apc_file)
}

```

where `versions.csv` is a two-column table of `version` and `id`.  (I've put it on the `inst/extdata` path because ideally instead of doing `read_csv()` directly from github, you would also add a fallback method with tryCatch or something to have it read a version of the lookup table packaged within the R package.  This would insure that everything would still work even if the user is entirely offline provided they have accessed the data file at least once before and thus have a local cached copy.

**Comment by dfalster** [comment]
Cool stuff! 

Yes, we really want to avoid having to reinstall R code to access a new version of the data. I was thinking we'd eventually start pushing the APC data to zenodo instead of storing on GitHub. Then we could query Zenodo for a lost of versions, like we do in https://github.com/traitecoevo/austraits/

E.g., see https://github.com/traitecoevo/austraits/blob/5f701047259f41a3808fedb56187677a7a68ac23/R/load_austraits.R#L87

You can then access details on doi, files, etc
```
  res <- jsonlite::read_json("https://zenodo.org/api/records/?q=conceptrecid:3568417&all_versions=true",
                               simplifyVector = T)

> res$hits$hits$files[[1]]
                                bucket                             checksum                 key                                                                                  self     size type
1 c811dbf7-3276-4001-9fba-edbdc4946bd6 md5:61b36a86930f6ffb073f4e189bbd5723 austraits-3.0.1.rds https://zenodo.org/api/files/c811dbf7-3276-4001-9fba-edbdc4946bd6/austraits-3.0.1.rds 12284561  rds
2 c811dbf7-3276-4001-9fba-edbdc4946bd6 md5:37790cce053fd9f4cca3c08c608d8301 austraits-3.0.1.zip https://zenodo.org/api/files/c811dbf7-3276-4001-9fba-edbdc4946bd6/austraits-3.0.1.zip 14737754  zip
3 c811dbf7-3276-4001-9fba-edbdc4946bd6 md5:7acc976f03d7c63f4b234c006da998f7     dictionary.html     https://zenodo.org/api/files/c811dbf7-3276-4001-9fba-edbdc4946bd6/dictionary.html  1677858 html
4 c811dbf7-3276-4001-9fba-edbdc4946bd6 md5:903af9bd10b1c5f54ab1357177a1c299             NEWS.md             https://zenodo.org/api/files/c811dbf7-3276-4001-9fba-edbdc4946bd6/NEWS.md    36673   md
5 c811dbf7-3276-4001-9fba-edbdc4946bd6 md5:48f97bf7f5cda8b5e855897ac7584a8d          readme.txt          https://zenodo.org/api/files/c811dbf7-3276-4001-9fba-edbdc4946bd6/readme.txt     9906  txt

#


res$hits$hits$metadata %>% select(doi, publication_date, version)
                      doi publication_date version
1  10.5281/zenodo.5099552       2021-07-14  v3.0.1
2  10.5281/zenodo.3568429       2019-12-09  v0.9.0
3  10.5281/zenodo.7583087       2023-01-30  v4.1.0
4  10.5281/zenodo.4316550       2020-12-11  v2.1.0
5  10.5281/zenodo.4316516       2020-07-08  v2.0.0
6  10.5281/zenodo.3568418       2019-12-09  v0.1.0
7  10.5281/zenodo.7368074       2022-11-27  v4.0.0
8  10.5281/zenodo.3583418       2019-12-09  v0.9.1
9  10.5281/zenodo.5112001       2021-07-14  v3.0.2
```

**Comment by cboettig** [comment]
@dfalster beautiful!  yup, precisely.  this is a much better way of creating the metadata table than my example above with a hypothetical `versions.csv` table.

**Comment by cboettig** [comment]
Quick proof-of-principle based on @dfalster 's example

```r
## determine the checksum of the most recent release
res <- jsonlite::read_json("https://zenodo.org/api/records/?q=conceptrecid:3568417&all_versions=true", simplify=FALSE)

dates <- purrr::map_chr(res$hits$hits, "created")
latest <- which.max(lubridate::as_datetime(dates))

key <- purrr::map_chr(res$hits$hits[[latest]]$files, "key")
checksum <- purrr::map_chr(res$hits$hits[[latest]]$files, "checksum")

# grab content identifier of the RDS file, say
rds_id <- checksum[grepl("[.]rds", key)]
id <- paste0("hash://", gsub(":", "/", rds_id))

# contentid part!
rds <- contentid::resolve(id, store=TRUE)

# now we can read in the file:
austraits <- readr::read_rds(rds)
```

Note that the `contentid::resolve()` line should take a few seconds to execute the first time it is run, but on subsequent calls should be nearly instant since it will find an `md5` match in the local cache before touching the network.  


Potential issue: with some quick testing, it looks like the Zenodo search API is doing something weird about search results for md5 sums in a versioned product when requesting a version that isn't the latest.  I'm following up with the Zenodo team about that.  



In this case, it's not really necessary though, because Zenodo is (presumably) giving permanent and version stable URLs for the content.  This means it's not really necessary to check hashes, we can just trust Zenodo, e.g.

```
local_copy <- file.path(dir, key)
if( ! file.exists(local_copy) { {
  download.file(url, local_copy)
}
```

Provided the file name already has a version in it (as yours does), and the URLs are stable and version specific, this should be a pretty robust and logically simple way of doing a download cache with nothing fancy.

Those ~ 4 lines are longer than the one-line `contentid::resolve()` and are tied to Zenodo URLs rather than being able to grab from any repository or URL, and from a technical guarantee URLs aren't promised to be stable (which is why DOIs were created in the first place).  But it's probably pretty good.

**Comment by cboettig** [comment]
ah, heard back from the Zenodo devs about my issue with non-latest versions and was of course my error in missing an extra "all_versions=1" parameter in the search API.  I can push a fix to CRAN shortly.

**Comment by wcornwell** [comment]
this is waiting for #34

**Comment by dfalster** [comment]
Closing this as basic contentID workflow is implemented. We're still evolving archiving of data on Zenodo, but this is followed up in #34.

**Comment by fontikar** [comment]
Carl added some great documentation about contentid [here](https://github.com/cboettig/contentid) useful for later!!!
