### ISSUE TITLE
Unmatched species - unsure of reason

### ISSUE THREAD

**Issue by rubysaltbush** [traitecoevo/APCalign#5]
A small number of species from my test dataset didn't match using apcnames but did match when I searched for them on https://biodiversity.org.au/nsl/services/APC using the predictive text function. I'm unsure whether these didn't match because of the version of APC used by apcnames or because of some sort of syntax issue. All were species with a "sp" in the middle of the species name (see below).

<img width="1178" alt="Screen Shot 2020-09-03 at 11 07 15 am" src="https://user-images.githubusercontent.com/68254917/92059848-a6c58180-edd5-11ea-8330-5a773dd1c72b.png">

**Comment by dfalster** [comment]
Ah, yes. 

They may have been excluded because 

1. Of the generic rule of excluding [anything ending in sp.](https://github.com/traitecoevo/apcnames/blob/b169266255397530821bbece9c63d36837eb3cc6/R/clean_names.R#L111) (ass also #3)
2. The number of character differences is bigger than what's allowed for automated matching. Records with `sp.` in the middle are more likely to suffer here, because they often have long place names following. 

Options for number 2 is to make the allowable distances an OR rather then AND. [Currently](https://github.com/traitecoevo/apcnames/blob/b169266255397530821bbece9c63d36837eb3cc6/R/clean_names.R#L171) it's

```
## Within allowable number of characters (absolute)
min_dist_abs_c <= max_distance_abs &
## Within allowable number of characters (relative)
min_dist_per_c <= max_distance_rel &
...
```

**Comment by dfalster** [comment]
Ruby, I can't read the original_name in your screen short, can you provide your table above with `original_name` and `could_match` both as text, and with link to the APC name? 3 examples should be enough. Thanks!

**Comment by rubysaltbush** [comment]
Tabbed text attached :)

[unmatched_apcnames_unsure.txt](https://github.com/traitecoevo/apcnames/files/5165655/unmatched_apcnames_unsure.txt)

**Comment by ehwenk** [comment]
@rubysaltbush @fontikar I've just added all these examples to our test file and they are currently all being aligned correctly, so some other fix we've made recently has also fixed this bug. 

So I'm closing this issue
