### ISSUE TITLE
Non-unique aligned reason (match_06)

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/APCalign#52]
As I was writing the vignette, I noticed there are 2 `match_06`

 match_06. Automatic alignment with synonymous term among **accepted** canonical names in APC (2023-07-20)        
 match_06. Automatic alignment with synonymous term among **known** canonical names APC (2023-07-20)  

Can these be collapsed into one? or delineated as match_06A, match_6B to retain their nuances?

``` r
library(tidyverse)
library(janitor)
#> 
#> Attaching package: 'janitor'
#> The following objects are masked from 'package:stats':
#> 
#>     chisq.test, fisher.test
library(ausflora) 

resources <- load_taxonomic_resources(stable_or_current_data = "stable")
#> Loading resources...
#> Warning: Error in curl::curl_fetch_memory(url, handle = handle): Timeout was reached: [hash-archive.carlboettiger.info] Operation timed out after 2002 milliseconds with 0 bytes received
#> ...done

aligned_gbif_taxa <- gbif_lite |> 
  tidyr::drop_na(species) |>  
  dplyr::pull(species) |> 
  align_taxa(resources = resources)
#> Checking alignments of 127 taxa
#>   -> 0 names already matched; 0 names checked but without a match; 121 taxa yet to be checked

aligned_gbif_taxa |> 
  pull(aligned_reason) |> 
  tabyl() |> 
  tibble()
#> # A tibble: 5 × 3
#>   `pull(aligned_gbif_taxa, aligned_reason)`                            n percent
#>   <chr>                                                            <int>   <dbl>
#> 1 match_06. Automatic alignment with synonymous term among accept…   112 0.926  
#> 2 match_06. Automatic alignment with synonymous term among known …     6 0.0496 
#> 3 match_08. Automatic alignment with synonymous name in APNI (202…     1 0.00826
#> 4 match_14. Automatic alignment with species-level canonical name…     1 0.00826
#> 5 match_20. Rewording name to be recognised as genus rank, with g…     1 0.00826
```

<sup>Created on 2023-07-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by dfalster** [comment]
Thanks Fonti. Let's mark as A and B for now

**Comment by wcornwell** [comment]
My understanding of what `align_taxa` is doing is that it's actually should be described as:
`Automatic alignment with accepted canonical names in APC`
instead of 
`Automatic alignment with synonymous term among accepted canonical names in APC`
since the synonymous part comes later in the work flow (now).

**Comment by wcornwell** [comment]
or better yet, this could all be simplified to 

`accepted name in APC` 

and

`name present but not accepted in APC`

The code numbers and all that are good internal record keeping but there is no way they will be understood by the user.

**Comment by fontikar** [comment]
I like that idea that there should be front facing reasons for users and internal ones for us

**Comment by ehwenk** [comment]
I'm slowly removing all the codes from the messages. I'll retain them as codes that are documented under the column `still_to_match` (maybe with a new name like `match_code`) and then continue streamlining output messages. There is currently lots of duplication in the match_codes, because I was grouping similar matches under a single code. These can have `A`, `B`, etc. added for clarity

**Comment by ehwenk** [comment]
closed with https://github.com/traitecoevo/APCalign/commit/1ebf641d0d2249f2b9a99410f948d02747bae7a0
